

#公共配置与profiles选择无关
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: springboot.librarybook.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

---  #分隔线不能少

#开发配置
spring:
  profiles:
    active: dev

  datasource:
    name: datasource
    url: jdbc:mysql://localhost:3306/librarybook?serverTimezone=GMT&characterEncoding=UTF-8&characterSetResults=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: nima123456
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20